source "https://rubygems.org"

gem "jekyll", "~> 4.3.4"
gem "webrick", "~> 1.7"
gem "kramdown-parser-gfm"

group :jekyll_plugins do
  gem "jekyll-bookshop", "3.0.1"
  gem "jekyll-postcss-v2"
  gem "jekyll-local-assign"
  gem "octopress-paginate"
  gem "jekyll-sass-converter", "~> 2.2.0"
end
